#!/usr/bin/env bash
#----------------------------------------------------
# Descrição : teste sobre condicionais
# Versão    : 0.1
# Autor     : Arthur Gabriel <arthur.albuquerque@lsd.ufcg.edu.br>
# Data      : 05/01/2025
# Licensa   : GNU/GPL v3.0
#----------------------------------------------------
# Uso: ./test_condicionais ou /path/to/test_condicionais
#----------------------------------------------------

clear

echo "Testa se o número pedido pelo usuario é igual a 5"

read -p "Entre com um número entre 1 e 10 para teste: " numero

# Verificação se é um número
# =~ indica que a expressão da direita é uma REGEX ou expressão regular
# [0-9] indica qualquer caractere numérico (de 0 a 9), o + indica que um ou mais caracteres 
# consecutivos podem estar nesse conjunto
# o ^ indica o começo da entrada o $ indica o fim, portando isso fala que apenas números devem está na entrada
[[ $numero =~ ^[0-9]+$ ]] || echo "Não é um número" && exit 1


#Verificação de números

# le = less or equal
# -le verifica se o primeiro número é menor ou igual ao segundo
# ge = greater or equal
# -ge verifica se o primeiro número é maior ou igual ao segundo
[[ $numero -ge 11 || $numero -le 0 ]] && echo "Número tem que estar entre 1 e 10, tente novamente" && exit 1

#Comparações como são feitas
# eq é para verificar se são iguais
# eq = equals
[[ $numero -eq 5 ]] && echo "São iguais"

# lt é para verificar se o primeiro é menor que o segundo
# lt = less than
[[ $numero -lt 5 ]] && echo "O número é menor que 5"

# gt é para verificar se o primeiro é maior que o segundo
# gt = greater then
[[ $numero -gt 5 ]] && echo "O número é maior que 5"

exit 0
